steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/kloud4gcpdevops/yugansethu:$COMMIT_SHA', '-t', 'us.gcr.io/kloud4gcpdevops/yugansethu:latest',"--build-arg=JAR_FILE=kloud4devops-0.0.1-SNAPSHOT.jar", '.' ]
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/kloud4gcpdevops/yugansethu:latest' ]
  id: 'Push Docker Image'
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file devcluster.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=demo-btegbij --region=us-central1 --skaffold-file=skaffold.yaml
options:
  logging: CLOUD_LOGGING_ONLY