steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/kloud4cidepipeline/yugansethu/gcpcloud:v1", "--build-arg=JAR_FILE=kloud4devops-0.0.1-SNAPSHOT.jar", "."]
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/kloud4cidepipeline/yugansethu/gcpcloud:v1' ]
  id: 'Push Docker Image'
  
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file devcluster.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gkecicd-pipeline --region=us-central1 --from-k8s-manifest=./kuberntes/app.yaml
options:
  logging: CLOUD_LOGGING_ONLY