apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gkecicd-pipelines
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev GKE cluster
gke:
 cluster: projects/kloud4academydevops/locations/us-central1/clusters/kloud4academy-cluster