apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/kloud4gcpdevops/locations/us-central1/targets/dev
  
#  projects/kloud4gcpdevops/locations/us-central1/clusters/kloud4acdmy-devops