apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpk-servic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gcpk-servic
  template:
    metadata:
      labels:
        run: gcpk-servic
    spec:
      containers:
      - name: gcpk-servic
        image: us.gcr.io/kloud4cidepipeline/yugansethu/gcpcloud:v1
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: gcpk-servic
  labels:
    run: gcpk-servic
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    run: gcpk-servic