pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    stages {

        stage("Build") {
            steps { buildApp() }
		}

        stage("Deploy - Dev") {
            steps { deploy('dev') }
		}

	}
}


// steps
def buildApp() {
	dir ('jenkin' ) {
		def appImage = docker.build("hands-on-jenkins/myapp:${BUILD_NUMBER}")
	}
}

def deploy(environment) {

	def containerName = ''
	def port = ''

	if ("${environment}" == 'dev') {
		containerName = "app_dev"
		port = "8888"
	} 
	else {
		println "Environment not valid"
		System.exit(0)
	}

	bat "docker ps -f name=${containerName} -q"
	bat "docker ps -a -f name=${containerName} -q | xargs docker rm"
	bat "docker run --publish 8082:8082 --name ${containerName} hands-on-jenkins/myapp:${BUILD_NUMBER}"

}
